# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dr. Emrah Özcan
email: dr@emrahozcan.com.tr
email2: eozcan@yildiz.edu.tr
phone: 00902123834869
phone_nice: +90 (212) 383 4869
description: >- # this means to ignore newlines until "baseurl:"
   "...dum loquimur, fugerit invida aetas: carpe diem, quam minimum credula postero."
   As we speak cruel time is fleeing. Seize the day, believing as little as possible in the morrow.
   — Horace, Odes (c. 23 BC and 13 BC), Book I, ode xi, line 8.
baseurl: "/site" # the subpath of your site, e.g. /blog
url: "https://mrhzcn.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mrhzcn
github_username:  mrhzcn
googlescholar_username: I32BxyoAAAAJ
researchgate_username: Emrah_Oezcan2
orcid_username: 0000-0001-9340-5485
academia_username: EmrahOzcan
mendeley_username: emrah-zcan3
publons_username: Q-8901-2019

# Build settings
markdown: kramdown
theme: primer
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
